const continents = [
  {
    id: "europe",
    image: "europe.jpg",
    name: "Europe",
    info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    numberOfCountries: "50",
    numberOfLanguages: "60",
    numberOfCities: "27",
    citiesPlus100: [
      {
        name: "London",
        image: "london.jpg",
        country: "England",
        code: "GBR",
      },
      {
        name: "Paris",
        image: "paris.jpg",
        country: "France",
        code: "FRA",
      },
      {
        name: "Rome",
        image: "rome.jpg",
        country: "Italy",
        code: "ITA",
      },
      {
        name: "Prague",
        image: "prague.jpg",
        country: "Czech Repulic",
        code: "CZE",
      },
    ],
  },
  {
    id: "africa",
    image: "africa.jpg",
    name: "Africa",
    info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    numberOfCountries: "54",
    numberOfLanguages: "~1000",
    numberOfCities: "13",
    citiesPlus100: [
      {
        name: "Johannesburg",
        image: "johannesburg.jpg",
        country: "South Africa",
        code: "ZAF",
      },
      {
        name: "Cape Town",
        image: "cape-town.jpg",
        country: "South Africa",
        code: "ZAF",
      },
      {
        name: "Cairo",
        image: "cairo.jpg",
        country: "Egypt",
        code: "EGY",
      },
      {
        name: "Lagos",
        image: "lagos.jpg",
        country: "Nigeria",
        code: "NGA",
      },
    ],
  },
  {
    id: "south-america",
    image: "south-america.jpg",
    name: "South America",
    info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    numberOfCountries: "12",
    numberOfLanguages: "37",
    numberOfCities: "13",
    citiesPlus100: [
      {
        name: "Rio de Janeiro",
        image: "rio-de-janeiro.jpg",
        country: "Brazil",
        code: "BRA",
      },
      {
        name: "Cusco",
        image: "cusco.jpg",
        country: "Peru",
        code: "PER",
      },
      {
        name: "Santiago",
        image: "santiago.jpg",
        country: "Chile",
        code: "CHL",
      },
      {
        name: "Ushuaia",
        image: "ushuaia.jpg",
        country: "Argentina",
        code: "ARG",
      },
    ],
  },
  {
    id: "asia",
    image: "asia.jpg",
    name: "Asia",
    info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    numberOfCountries: "48",
    numberOfLanguages: "~2300",
    numberOfCities: "13",
    citiesPlus100: [
      {
        name: "Tokyo",
        image: "tokyo.jpg",
        country: "Japan",
        code: "JAP",
      },
      {
        name: "Singapore",
        image: "singapore.jpg",
        country: "Singapore",
        code: "SGP",
      },
      {
        name: "Seoul",
        image: "seoul.jpg",
        country: "South Korea",
        code: "KOR",
      },
      {
        name: "Beijing",
        image: "beijing.jpg",
        country: "China",
        code: "CHN",
      },
    ],
  },
  {
    id: "oceania",
    image: "australia.jpg",
    name: "Oceania",
    info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    numberOfCountries: "14",
    numberOfLanguages: "5",
    numberOfCities: "16",
    citiesPlus100: [
      {
        name: "Sidney",
        image: "sidney.jpg",
        country: "Australia",
        code: "AUS",
      },
      {
        name: "Tasmania",
        image: "tasmania.jpg",
        country: "Australia",
        code: "AUS",
      },
      {
        name: "Nuku Hiva",
        image: "nuku-hiva.jpg",
        country: "French Polynesia",
        code: "PYF",
      },
      {
        name: "wellington",
        image: "london.jpg",
        country: "New Zealand",
        code: "NZL",
      },
    ],
  },
];

export default continents;
